### PR TITLE
Support alternate `tox.ini` locations.

### PR DESCRIPTION
**Pull request by jsirois**

### CODE REVIEW

**Comment by jsirois** [comment]
This is being used successfully in this branch: https://github.com/pantsbuild/pex/pull/2198

**Review by cognifloyd — APPROVED** [review]

**Comment by jsirois** [comment]
Thanks for the review @cognifloyd. I think maybe the general Pants community thinks merging someone else's PR is OK, and in this case it was, but, in general, this seems very much not cool to do. I know I often have later thoughts and make adjustments before landing.

**Comment by cognifloyd** [comment]
@jsirois if you are actively working on a PR then you must include `WIP` in the title, or mark it as draft (a core GitHub feature). Once it is out of draft, then any maintainer can and SHOULD merge to avoid PRs piling up.

I have been a mere contributor (not a maintainer) on many projects where my PR sat approved but unmerged for months because the maintainers were used to the closed source practice of PR authors merging their own PR. The last maintainer that approves is responsible for merging to ensure that doesn't happen.

**Comment by jsirois** [comment]
Ok, I hate that idea. But at least I know your reasoning.

**Pull request merged**
